list=["london","France","canada","portugal","italy"]
print(list)
list_sorted = sorted(list)
print(list_sorted)
print(list)
list.reverse()
print(list)
list.reverse()
print(list)
list.sort()
print(list)
list.sort(reverse=True)
print(list)